language: node_js
node_js:
  - "node"
  - "6"
  - "4"

cache:
  yarn: true
  directories:
    - $HOME/.npm
    - $HOME/.cache

before_install:
  # Since we override the install hooks, we need to setup Yarn on our own
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
  - yarn global add bower
  - bower --version

install:
  - yarn install --no-lockfile

script:
  - yarn test
